@baseUrl = http://localhost:3000

### 0. Fazer Login para pegar o Token
# @name loginUser
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "paciente.completo@glicemy.com",
  "password": "senha_segura_123"
}

###
@authToken = {{loginUser.response.body.token}}

### 1. Registrar Altura
POST {{baseUrl}}/api/height
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "heightValue": 1.75,
  "measurementDateTime": "2026-06-25T08:00:00.000Z"
}

###

### 2. Listar Historico de Altura
GET {{baseUrl}}/api/height
Authorization: Bearer {{authToken}}

###

### 3. Buscar um registro especifico
@recordId = cole_o_id_uuid_aqui

GET {{baseUrl}}/api/height/{{recordId}}
Authorization: Bearer {{authToken}}

###

### 4. Atualizar registro
PUT {{baseUrl}}/api/height/{{recordId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "heightValue": 1.76
}

###

### 5. Deletar registro
DELETE {{baseUrl}}/api/height/{{recordId}}
Authorization: Bearer {{authToken}}