@baseUrl = http://localhost:3000

### 0. Fazer Login para pegar o Token
# @name loginUser
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "paciente.completo@glicemy.com",
  "password": "senha_segura_123"
}

###
@authToken = {{loginUser.response.body.token}}

### 1. Buscar Perfil (Meu Usuario)
GET {{baseUrl}}/api/users/me
Authorization: Bearer {{authToken}}

###

### 2. Atualizar Perfil
PUT {{baseUrl}}/api/users/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "phone": "79988887777",
  "diabetesType": "type2",
  "diagnosisYear": 2020
}

###

### 3. Excluir Conta (CUIDADO: Isso apagara TUDO associado a este usuario)
DELETE {{baseUrl}}/api/users/me
Authorization: Bearer {{authToken}}