@baseUrl = http://localhost:3000

### 0. Fazer Login para pegar o Token
# @name loginUser
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "paciente.completo@glicemy.com",
  "password": "senha_segura_123"
}

###
@authToken = {{loginUser.response.body.token}}

### 1. Registrar HbA1c (Hemoglobina Glicada)
POST {{baseUrl}}/api/hba1c
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "hba1cValue": 5.8,
  "notes": "Exame de rotina trimestral",
  "measurementDate": "2026-06-25T00:00:00.000Z"
}

###

### 2. Listar Historico de HbA1c
GET {{baseUrl}}/api/hba1c
Authorization: Bearer {{authToken}}

###

### 3. Buscar um registro especifico
@recordId = cole_o_id_uuid_aqui

GET {{baseUrl}}/api/hba1c/{{recordId}}
Authorization: Bearer {{authToken}}

###

### 4. Atualizar registro
PUT {{baseUrl}}/api/hba1c/{{recordId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "hba1cValue": 5.7,
  "notes": "Correcao do valor lido no laudo oficial"
}

###

### 5. Deletar registro
DELETE {{baseUrl}}/api/hba1c/{{recordId}}
Authorization: Bearer {{authToken}}